### ISSUE TITLE
typo in the Stars title

### ISSUE THREAD

**Issue by ggbecker** [marcusburghardt/CommunityMon#1]
https://github.com/marcusburghardt/CommunityMon/blob/4469a08aeb2510ddcbbda1aa9593b09e64f65611/Stack/gfn_env/dashboards/Content_Repository.json#L96

https://github.com/marcusburghardt/CommunityMon/blob/4469a08aeb2510ddcbbda1aa9593b09e64f65611/Stack/gfn_env/dashboards/Content_Repository.json#L101

there is an extra `t`

**Comment by marcusburghardt** [comment]
Thanks for reporting @ggbecker . I just checked this issue and confirmed it was already fixed by some previous update in this Dashboard.
